### ISSUE TITLE
Rupert Windows Issue

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/stassets#32]
David,

Just tested it and I see that Rupert works just fine on Windows aside from one small bug... basically when I have a `/src/client/person/template.html` ... I get the following:

![bug](http://i.imgur.com/IUJYAQh.png)

...one can do `window.Templates['/person']`, but clearly that's hacky

**Comment by DavidSouther** [comment]
@iaspenDOL ran into that; he and I worked through it, but it seems the fix didn't make it upstream.

**Comment by DavidSouther** [comment]
Fixed in 0.3.14

**Comment by MatthewVita** [comment]
nice!
